spring:
  profiles:
    active: dev
  application:
    name: working-user-manage
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/working-user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 88888888


server:
  port: 8890
  max-http-header-size: 4048576
  tomcat:
    max-http-post-size: -1  #请求参数长度

loginTime: 604800

#数据库名称
project:
  database: mysql

#mybatis-plus配置
mybatis-plus:
  configuration:
    #sql日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名匹配
    map-underscore-to-camel-case: true
    #mapper文件
  mapper-locations: classpath:mapper/${project.database}/**/*.xml,classpath:mapper/*.xml
  #数据库实体类的包全路径，方便在mapper.xml中不许使用实体类的全路径，写类名就行（不区分大小写）
  type-aliases-package: com.zhuang.mp.entity
  global-config:
    db-config:
      #逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: deleted

---
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        username: nacos
        password: nacos
ribbon:
  eager-load:
    clients:


